USE video_flow;

SET @exist = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'videos' AND COLUMN_NAME = 'share_count');
SET @sql = IF(@exist=0, 'ALTER TABLE videos ADD COLUMN share_count BIGINT NOT NULL DEFAULT 0;', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @exist = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'videos' AND COLUMN_NAME = 'view_count');
SET @sql = IF(@exist=0, 'ALTER TABLE videos ADD COLUMN view_count BIGINT NOT NULL DEFAULT 0;', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
